server:
  port: 8959
  
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mini_project_3
#    username: root
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://herokutest.ci3casdwagpp.ap-south-1.rds.amazonaws.com/aws
    username: admin
    password: mypassword
       
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
  
    hibernate:
      ddl-auto: update
    show-sql: true       
        
  mvc:
   pathmatch:
      matching-strategy: ant-path-matcher